name: Build Android
on: [push, pull_request]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false

jobs:

  # Game
  game-windows:
    if: ${{ false }}
    name: Game (Android, Release ARM64)
    runs-on: "windows-2022"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Vulkan
      uses: ./.github/actions/vulkan
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Print .NET info
      run: |
        dotnet --info
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Build
      run: |
        .\Development\Scripts\Windows\CallBuildTool.bat -build -log -arch=ARM64 -platform=Android -configuration=Release -buildtargets=FlaxGame
