name: Build macOS
on: [push, pull_request]

env:
  VULKAN_SDK_ROOT: /Users/runner/VulkanSDK
  VULKAN_SDK: /Users/runner/VulkanSDK/macOS

jobs:

  # Editor
  editor-mac:
    name: Editor (Mac, Development x64)
    runs-on: "macos-latest"
    steps:
    - name: Setup Vulkan
      run: |
        curl -LO "https://sdk.lunarg.com/sdk/download/latest/mac/vulkan-sdk.dmg"
        hdiutil attach vulkan-sdk.dmg -mountpoint /Volumes/vulkan-sdk
        sudo "/Volumes/vulkan-sdk/InstallVulkan.app/Contents/MacOS/InstallVulkan" --root "$VULKAN_SDK_ROOT" --accept-licenses --default-answer --confirm-command install
        echo Vulkan SDK installed!
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Build
      run: |
        ./Development/Scripts/Mac/CallBuildTool.sh -build -log -arch=x64 -platform=Mac -configuration=Development -buildtargets=FlaxEditor

  # Game
  game-mac:
    name: Game (Mac, Release x64)
    runs-on: "macos-latest"
    steps:
    - name: Setup Vulkan
      run: |
        curl -LO "https://sdk.lunarg.com/sdk/download/latest/mac/vulkan-sdk.dmg"
        hdiutil attach vulkan-sdk.dmg -mountpoint /Volumes/vulkan-sdk
        sudo "/Volumes/vulkan-sdk/InstallVulkan.app/Contents/MacOS/InstallVulkan" --root "$VULKAN_SDK_ROOT" --accept-licenses --default-answer --confirm-command install
        echo Vulkan SDK installed!
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Build
      run: |
        ./Development/Scripts/Mac/CallBuildTool.sh -build -log -arch=x64 -platform=Mac -configuration=Release -buildtargets=FlaxGame
