name: Build Linux
on: [push, pull_request]

env:
  VULKAN_SDK_VER: 1.2.198.1
  VULKAN_SDK_ROOT: /home/runner/work/VulkanSDK
  VULKAN_SDK: /home/runner/work/VulkanSDK/1.2.198.1/x86_64

jobs:

  # Editor
  editor-linux:
    name: Editor (Linux, Development x64)
    runs-on: "ubuntu-20.04"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/*
        sudo cp -f .github/workflows/build_linux_sources.list /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install libx11-dev libxcursor-dev libxinerama-dev build-essential gettext libtool libtool-bin libpulse-dev libasound2-dev libjack-dev portaudio19-dev
    - name: Setup Vulkan
      run: |
        wget "https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VER/linux/vulkan-sdk.tar.gz" --no-verbose -O vulkan-sdk.tar.gz
        mkdir $VULKAN_SDK_ROOT
        tar -xf vulkan-sdk.tar.gz -C $VULKAN_SDK_ROOT
        echo Vulkan SDK installed!
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Build
      run: |
        ./Development/Scripts/Linux/CallBuildTool.sh -build -log -arch=x64 -platform=Linux -configuration=Development -buildtargets=FlaxEditor

  # Game
  game-linux:
    name: Game (Linux, Release x64)
    runs-on: "ubuntu-20.04"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install libx11-dev libxcursor-dev libxinerama-dev
    - name: Setup Vulkan
      run: |
        wget "https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VER/linux/vulkan-sdk.tar.gz" --no-verbose -O vulkan-sdk.tar.gz
        mkdir $VULKAN_SDK_ROOT
        tar -xf vulkan-sdk.tar.gz -C $VULKAN_SDK_ROOT
        echo Vulkan SDK installed!
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Build
      run: |
        ./Development/Scripts/Linux/CallBuildTool.sh -build -log -arch=x64 -platform=Linux -configuration=Release -buildtargets=FlaxGame
