name: Tests
on: [push, pull_request]

jobs:

  # Tests on Linux
  tests-linux:
    if: ${{ false }}
    name: Tests (Linux)
    runs-on: "ubuntu-20.04"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Print .NET info
      run: |
        dotnet --info
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/*
        sudo cp -f .github/workflows/build_linux_sources.list /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install libx11-dev libxcursor-dev libxinerama-dev build-essential gettext libtool libtool-bin libpulse-dev libasound2-dev libjack-dev portaudio19-dev
    - name: Build
      run: |
        ./GenerateProjectFiles.sh -vs2022
        ./Development/Scripts/Linux/CallBuildTool.sh -build -log -arch=x64 -platform=Linux -configuration=Development -buildtargets=FlaxTestsTarget
        ./Development/Scripts/Linux/CallBuildTool.sh -build -log -arch=x64 -platform=Linux -configuration=Debug -buildtargets=FlaxEditor -BuildBindingsOnly
        ./Development/Scripts/Linux/CallBuildTool.sh -build -log -arch=x64 -platform=Linux -configuration=Debug -buildtargets="FlaxEngine.Tests"
        ./Development/Scripts/Linux/CallBuildTool.sh -build -log -arch=x64 -platform=Linux -configuration=Debug -buildtargets="Flax.Build.Tests"
    - name: Test
      run: |
        Binaries/Editor/Linux/Development/FlaxTests
        dotnet Source/Platforms/DotNet/NUnit/nunit3-netcore-console.dll Binaries/Tools/FlaxEngine.Tests.dll
        dotnet Source/Platforms/DotNet/NUnit/nunit3-netcore-console.dll Binaries/Tools/Flax.Build.Tests.dll
    - name: Test UseLargeWorlds
      run: |
        ./Development/Scripts/Linux/CallBuildTool.sh -build -log -arch=x64 -platform=Linux -configuration=Development -buildtargets=FlaxTestsTarget -UseLargeWorlds=true
        Binaries/Editor/Linux/Development/FlaxTests

  # Tests on Windows
  tests-windows:
    if: ${{ false }}
    name: Tests (Windows)
    runs-on: "windows-2022"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Print .NET info
      run: |
        dotnet --info
    - name: Checkout LFS
      run: |
        git lfs version
        git lfs pull
    - name: Build
      run: |
        .\GenerateProjectFiles.bat -vs2022
        .\Development\Scripts\Windows\CallBuildTool.bat -build -log -arch=x64 -platform=Windows -configuration=Development -buildtargets=FlaxTestsTarget
        .\Development\Scripts\Windows\CallBuildTool.bat -build -log -arch=x64 -platform=Windows -configuration=Debug -buildtargets=FlaxEditor -BuildBindingsOnly
        .\Development\Scripts\Windows\CallBuildTool.bat -build -log -arch=x64 -platform=Windows -configuration=Debug -buildtargets="FlaxEngine.Tests"
        .\Development\Scripts\Windows\CallBuildTool.bat -build -log -arch=x64 -platform=Windows -configuration=Debug -buildtargets="Flax.Build.Tests"
    - name: Test
      run: |
        Binaries\Editor\Win64\Development\FlaxTests.exe
        Source\Platforms\DotNet\NUnit\nunit3-netcore-console.exe Binaries\Tools\FlaxEngine.Tests.dll
        Source\Platforms\DotNet\NUnit\nunit3-netcore-console.exe Binaries\Tools\Flax.Build.Tests.dll
